name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore BigDataProject
    - name: Build
      run: dotnet build --no-restore BigDataProject
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RankedOrNot
        path: D:\a\big_data_project\BigDataProject\BigDataProject\bin\Debug\net8.0-windows
